// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Backup struct {
	ID             uuid.UUID
	DatabaseID     uuid.UUID
	DestinationID  uuid.NullUUID
	Name           string
	CronExpression string
	TimeZone       string
	IsActive       bool
	DestDir        string
	RetentionDays  int16
	OptDataOnly    bool
	OptSchemaOnly  bool
	OptClean       bool
	OptIfExists    bool
	OptCreate      bool
	OptNoComments  bool
	CreatedAt      time.Time
	UpdatedAt      sql.NullTime
	IsLocal        bool
}

type Database struct {
	ID               uuid.UUID
	Name             string
	ConnectionString []byte
	PgVersion        string
	CreatedAt        time.Time
	UpdatedAt        sql.NullTime
	TestOk           sql.NullBool
	TestError        sql.NullString
	LastTestAt       sql.NullTime
}

type Destination struct {
	ID         uuid.UUID
	Name       string
	BucketName string
	AccessKey  []byte
	SecretKey  []byte
	Region     string
	Endpoint   string
	CreatedAt  time.Time
	UpdatedAt  sql.NullTime
	TestOk     sql.NullBool
	TestError  sql.NullString
	LastTestAt sql.NullTime
}

type Execution struct {
	ID         uuid.UUID
	BackupID   uuid.UUID
	Status     string
	Message    sql.NullString
	Path       sql.NullString
	StartedAt  time.Time
	UpdatedAt  sql.NullTime
	FinishedAt sql.NullTime
	DeletedAt  sql.NullTime
	FileSize   sql.NullInt64
}

type Restoration struct {
	ID          uuid.UUID
	ExecutionID uuid.UUID
	DatabaseID  uuid.NullUUID
	Status      string
	Message     sql.NullString
	StartedAt   time.Time
	UpdatedAt   sql.NullTime
	FinishedAt  sql.NullTime
}

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     []byte
	Ip        string
	UserAgent string
	CreatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Name         string
	Email        string
	Password     sql.NullString
	CreatedAt    time.Time
	UpdatedAt    sql.NullTime
	OidcProvider sql.NullString
	OidcSubject  sql.NullString
}

type Webhook struct {
	ID        uuid.UUID
	Name      string
	IsActive  bool
	EventType string
	TargetIds []uuid.UUID
	Url       string
	Method    string
	Headers   sql.NullString
	Body      sql.NullString
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type WebhookExecution struct {
	ID          uuid.UUID
	WebhookID   uuid.UUID
	ReqMethod   sql.NullString
	ReqHeaders  sql.NullString
	ReqBody     sql.NullString
	ResStatus   sql.NullInt16
	ResHeaders  sql.NullString
	ResBody     sql.NullString
	ResDuration sql.NullInt32
	CreatedAt   time.Time
}
