-- This file is auto-generated by /app/scripts/sqlc-prebuild.ts. DO NOT EDIT.

-- file: /app/internal/service/webhooks/update_webhook.sql
-- name: WebhooksServiceUpdateWebhook :one
UPDATE webhooks
SET
  name = COALESCE(sqlc.narg('name'), name),
  is_active = COALESCE(sqlc.narg('is_active'), is_active),
  event_type = COALESCE(sqlc.narg('event_type'), event_type),
  target_ids = COALESCE(sqlc.narg('target_ids'), target_ids),
  url = COALESCE(sqlc.narg('url'), url),
  method = COALESCE(sqlc.narg('method'), method),
  headers = COALESCE(sqlc.narg('headers'), headers),
  body = COALESCE(sqlc.narg('body'), body)
WHERE id = @webhook_id
RETURNING *;

-- file: /app/internal/service/webhooks/run_webhook.sql
-- name: WebhooksServiceGetWebhooksToRun :many
SELECT * FROM webhooks
WHERE is_active = true
AND event_type = @event_type
AND @target_id::UUID = ANY(target_ids);

-- file: /app/internal/service/webhooks/run_webhook.sql
-- name: WebhooksServiceCreateWebhookExecution :one
INSERT INTO webhook_executions (
  webhook_id, req_method, req_headers, req_body,
  res_status, res_headers, res_body, res_duration
)
VALUES (
  @webhook_id, @req_method, @req_headers, @req_body,
  @res_status, @res_headers, @res_body, @res_duration
)
RETURNING *;


-- file: /app/internal/service/webhooks/paginate_webhooks.sql
-- name: WebhooksServicePaginateWebhooksCount :one
SELECT COUNT(*) FROM webhooks;

-- file: /app/internal/service/webhooks/paginate_webhooks.sql
-- name: WebhooksServicePaginateWebhooks :many
SELECT * FROM webhooks
ORDER BY created_at DESC
LIMIT sqlc.arg('limit') OFFSET sqlc.arg('offset');


-- file: /app/internal/service/webhooks/paginate_webhook_executions.sql
-- name: WebhooksServicePaginateWebhookExecutionsCount :one
SELECT COUNT(*) FROM webhook_executions
WHERE webhook_id = @webhook_id;

-- file: /app/internal/service/webhooks/paginate_webhook_executions.sql
-- name: WebhooksServicePaginateWebhookExecutions :many
SELECT * FROM webhook_executions
WHERE webhook_id = @webhook_id
ORDER BY created_at DESC
LIMIT sqlc.arg('limit') OFFSET sqlc.arg('offset');

-- file: /app/internal/service/webhooks/get_webhook.sql
-- name: WebhooksServiceGetWebhook :one
SELECT * FROM webhooks WHERE id = @webhook_id;


-- file: /app/internal/service/webhooks/duplicate_webhook.sql
-- name: WebhooksServiceDuplicateWebhook :one
INSERT INTO webhooks
SELECT (
  webhooks
  #= hstore('id', uuid_generate_v4()::text)
  #= hstore('name', (webhooks.name || ' (copy)')::text)
  #= hstore('is_active', false::text)
  #= hstore('created_at', now()::text)
  #= hstore('updated_at', now()::text)
).*
FROM webhooks
WHERE webhooks.id = @webhook_id
RETURNING *;


-- file: /app/internal/service/webhooks/delete_webhook.sql
-- name: WebhooksServiceDeleteWebhook :exec
DELETE FROM webhooks WHERE id = @webhook_id;


-- file: /app/internal/service/webhooks/create_webhook.sql
-- name: WebhooksServiceCreateWebhook :one
INSERT INTO webhooks (
  name, is_active, event_type, target_ids,
  url, method, headers, body
) VALUES (
  @name, @is_active, @event_type, @target_ids,
  @url, @method, @headers, @body
) RETURNING *;


-- file: /app/internal/service/users/update_user.sql
-- name: UsersServiceUpdateUser :one
UPDATE users
SET
  name = COALESCE(sqlc.narg('name'), name),
  email = lower(COALESCE(sqlc.narg('email'), email)),
  password = COALESCE(sqlc.narg('password'), password)
WHERE id = @id
RETURNING *;


-- file: /app/internal/service/users/get_users_qty.sql
-- name: UsersServiceGetUsersQty :one
SELECT COUNT(*) FROM users;


-- file: /app/internal/service/users/get_user_by_email.sql
-- name: UsersServiceGetUserByEmail :one
SELECT * FROM users WHERE email = @email;


-- file: /app/internal/service/users/create_user.sql
-- name: UsersServiceCreateUser :one
INSERT INTO users (name, email, password)
VALUES (@name, lower(@email), @password)
RETURNING *;


-- file: /app/internal/service/users/change_password.sql
-- name: UsersServiceChangePassword :exec
UPDATE users
SET password = @password
WHERE id = @id;


-- file: /app/internal/service/executions/update_execution.sql
-- name: ExecutionsServiceUpdateExecution :one
UPDATE executions
SET
  status = COALESCE(sqlc.narg('status'), status),
  message = COALESCE(sqlc.narg('message'), message),
  path = COALESCE(sqlc.narg('path'), path),
  finished_at = COALESCE(sqlc.narg('finished_at'), finished_at),
  deleted_at = COALESCE(sqlc.narg('deleted_at'), deleted_at),
  file_size = COALESCE(sqlc.narg('file_size'), file_size)
WHERE id = @id
RETURNING *;


-- file: /app/internal/service/executions/soft_delete_expired_executions.sql
-- name: ExecutionsServiceGetExpiredExecutions :many
SELECT executions.*
FROM executions
JOIN backups ON executions.backup_id = backups.id
WHERE
  backups.retention_days > 0
  AND executions.status != 'deleted'
  AND executions.finished_at IS NOT NULL
  AND (
    executions.finished_at + (backups.retention_days || ' days')::INTERVAL
  ) < NOW();


-- file: /app/internal/service/executions/soft_delete_execution.sql
-- name: ExecutionsServiceGetExecutionForSoftDelete :one
SELECT
  executions.id as execution_id,
  executions.path as execution_path,

  backups.id as backup_id,
  backups.is_local as backup_is_local,

  destinations.bucket_name as destination_bucket_name,
  destinations.region as destination_region,
  destinations.endpoint as destination_endpoint,
  (
    CASE WHEN destinations.access_key IS NOT NULL
    THEN pgp_sym_decrypt(destinations.access_key, sqlc.arg('encryption_key')::TEXT)
    ELSE ''
    END
  ) AS decrypted_destination_access_key,
  (
    CASE WHEN destinations.secret_key IS NOT NULL
    THEN pgp_sym_decrypt(destinations.secret_key, sqlc.arg('encryption_key')::TEXT)
    ELSE ''
    END
  ) AS decrypted_destination_secret_key
FROM executions
INNER JOIN backups ON backups.id = executions.backup_id
LEFT JOIN destinations ON destinations.id = backups.destination_id
WHERE executions.id = @execution_id;

-- file: /app/internal/service/executions/soft_delete_execution.sql
-- name: ExecutionsServiceSoftDeleteExecution :exec
UPDATE executions
SET
  status = 'deleted',
  deleted_at = NOW()
WHERE id = @id;


-- file: /app/internal/service/executions/run_execution.sql
-- name: ExecutionsServiceGetBackupData :one
SELECT
  backups.is_active as backup_is_active,
  backups.is_local as backup_is_local,
  backups.dest_dir as backup_dest_dir,
  backups.opt_data_only as backup_opt_data_only,
  backups.opt_schema_only as backup_opt_schema_only,
  backups.opt_clean as backup_opt_clean,
  backups.opt_if_exists as backup_opt_if_exists,
  backups.opt_create as backup_opt_create,	
  backups.opt_no_comments as backup_opt_no_comments,

  pgp_sym_decrypt(databases.connection_string, @encryption_key) AS decrypted_database_connection_string,
  databases.pg_version as database_pg_version,

  destinations.bucket_name as destination_bucket_name,
  destinations.region as destination_region,
  destinations.endpoint as destination_endpoint,
  (
    CASE WHEN destinations.access_key IS NOT NULL
    THEN pgp_sym_decrypt(destinations.access_key, @encryption_key)
    ELSE ''
    END
  ) AS decrypted_destination_access_key,
  (
    CASE WHEN destinations.secret_key IS NOT NULL
    THEN pgp_sym_decrypt(destinations.secret_key, @encryption_key)
    ELSE ''
    END
  ) AS decrypted_destination_secret_key
FROM backups
INNER JOIN databases ON backups.database_id = databases.id
LEFT JOIN destinations ON backups.destination_id = destinations.id
WHERE backups.id = @backup_id;


-- file: /app/internal/service/executions/paginate_executions.sql
-- name: ExecutionsServicePaginateExecutionsCount :one
SELECT COUNT(executions.*)
FROM executions
INNER JOIN backups ON backups.id = executions.backup_id
INNER JOIN databases ON databases.id = backups.database_id
LEFT JOIN destinations ON destinations.id = backups.destination_id
WHERE
(
  sqlc.narg('backup_id')::UUID IS NULL
  OR
  backups.id = sqlc.narg('backup_id')::UUID
)
AND
(
  sqlc.narg('database_id')::UUID IS NULL
  OR
  databases.id = sqlc.narg('database_id')::UUID
)
AND
(
  sqlc.narg('destination_id')::UUID IS NULL
  OR
  destinations.id = sqlc.narg('destination_id')::UUID
);

-- file: /app/internal/service/executions/paginate_executions.sql
-- name: ExecutionsServicePaginateExecutions :many
SELECT
  executions.*,
  backups.name AS backup_name,
  databases.name AS database_name,
  databases.pg_version AS database_pg_version,
  destinations.name AS destination_name,
  backups.is_local AS backup_is_local
FROM executions
INNER JOIN backups ON backups.id = executions.backup_id
INNER JOIN databases ON databases.id = backups.database_id
LEFT JOIN destinations ON destinations.id = backups.destination_id
WHERE
(
  sqlc.narg('backup_id')::UUID IS NULL
  OR
  backups.id = sqlc.narg('backup_id')::UUID
)
AND
(
  sqlc.narg('database_id')::UUID IS NULL
  OR
  databases.id = sqlc.narg('database_id')::UUID
)
AND
(
  sqlc.narg('destination_id')::UUID IS NULL
  OR
  destinations.id = sqlc.narg('destination_id')::UUID
)
ORDER BY executions.started_at DESC
LIMIT sqlc.arg('limit') OFFSET sqlc.arg('offset');


-- file: /app/internal/service/executions/list_backup_executions.sql
-- name: ExecutionsServiceListBackupExecutions :many
SELECT * FROM executions
WHERE backup_id = @backup_id
ORDER BY started_at DESC;


-- file: /app/internal/service/executions/get_executions_qty.sql
-- name: ExecutionsServiceGetExecutionsQty :one
SELECT 
  COUNT(*) AS all,
  COALESCE(SUM(CASE WHEN status = 'running' THEN 1 ELSE 0 END), 0)::INTEGER AS running,
  COALESCE(SUM(CASE WHEN status = 'success' THEN 1 ELSE 0 END), 0)::INTEGER AS success,
  COALESCE(SUM(CASE WHEN status = 'failed' THEN 1 ELSE 0 END), 0)::INTEGER AS failed,
  COALESCE(SUM(CASE WHEN status = 'deleted' THEN 1 ELSE 0 END), 0)::INTEGER AS deleted
FROM executions;


-- file: /app/internal/service/executions/get_execution_download_link_or_path.sql
-- name: ExecutionsServiceGetDownloadLinkOrPathData :one
SELECT
  executions.path AS path,
  backups.is_local AS is_local,
  destinations.bucket_name AS bucket_name,
  destinations.region AS region,
  destinations.endpoint AS endpoint,
  destinations.endpoint as destination_endpoint,
  (
    CASE WHEN destinations.access_key IS NOT NULL
    THEN pgp_sym_decrypt(destinations.access_key, sqlc.arg('decryption_key')::TEXT)
    ELSE ''
    END
  ) AS decrypted_access_key,
  (
    CASE WHEN destinations.secret_key IS NOT NULL
    THEN pgp_sym_decrypt(destinations.secret_key, sqlc.arg('decryption_key')::TEXT)
    ELSE ''
    END
  ) AS decrypted_secret_key
FROM executions
INNER JOIN backups ON backups.id = executions.backup_id
LEFT JOIN destinations ON destinations.id = backups.destination_id
WHERE executions.id = @execution_id;


-- file: /app/internal/service/executions/get_execution.sql
-- name: ExecutionsServiceGetExecution :one
SELECT
  executions.*,
  databases.id AS database_id,
  databases.pg_version AS database_pg_version
FROM executions
INNER JOIN backups ON backups.id = executions.backup_id
INNER JOIN databases ON databases.id = backups.database_id
WHERE executions.id = @id;


-- file: /app/internal/service/executions/create_execution.sql
-- name: ExecutionsServiceCreateExecution :one
INSERT INTO executions (backup_id, status, message, path)
VALUES (@backup_id, @status, @message, @path)
RETURNING *;


-- file: /app/internal/service/restorations/update_restoration.sql
-- name: RestorationsServiceUpdateRestoration :one
UPDATE restorations
SET
  status = COALESCE(sqlc.narg('status'), status),
  message = COALESCE(sqlc.narg('message'), message),
  finished_at = COALESCE(sqlc.narg('finished_at'), finished_at)
WHERE id = @id
RETURNING *;


-- file: /app/internal/service/restorations/paginate_restorations.sql
-- name: RestorationsServicePaginateRestorationsCount :one
SELECT COUNT(restorations.*)
FROM restorations
INNER JOIN executions ON executions.id = restorations.execution_id
INNER JOIN backups ON backups.id = executions.backup_id
LEFT JOIN databases ON databases.id = restorations.database_id
WHERE
(
  sqlc.narg('execution_id')::UUID IS NULL
  OR
  restorations.execution_id = sqlc.narg('execution_id')::UUID
)
AND
(
  sqlc.narg('database_id')::UUID IS NULL
  OR
  restorations.database_id = sqlc.narg('database_id')::UUID
);

-- file: /app/internal/service/restorations/paginate_restorations.sql
-- name: RestorationsServicePaginateRestorations :many
SELECT
  restorations.*,
  databases.name AS database_name,
  backups.name AS backup_name
FROM restorations
INNER JOIN executions ON executions.id = restorations.execution_id
INNER JOIN backups ON backups.id = executions.backup_id
LEFT JOIN databases ON databases.id = restorations.database_id
WHERE
(
  sqlc.narg('execution_id')::UUID IS NULL
  OR
  restorations.execution_id = sqlc.narg('execution_id')::UUID
)
AND
(
  sqlc.narg('database_id')::UUID IS NULL
  OR
  restorations.database_id = sqlc.narg('database_id')::UUID
)
ORDER BY restorations.started_at DESC
LIMIT sqlc.arg('limit') OFFSET sqlc.arg('offset');


-- file: /app/internal/service/restorations/get_restorations_qty.sql
-- name: RestorationsServiceGetRestorationsQty :one
SELECT 
  COUNT(*) AS all,
  COALESCE(SUM(CASE WHEN status = 'running' THEN 1 ELSE 0 END), 0)::INTEGER AS running,
  COALESCE(SUM(CASE WHEN status = 'success' THEN 1 ELSE 0 END), 0)::INTEGER AS success,
  COALESCE(SUM(CASE WHEN status = 'failed' THEN 1 ELSE 0 END), 0)::INTEGER AS failed
FROM restorations;


-- file: /app/internal/service/restorations/create_restoration.sql
-- name: RestorationsServiceCreateRestoration :one
INSERT INTO restorations (execution_id, database_id, status, message)
VALUES (@execution_id, @database_id, @status, @message)
RETURNING *;


-- file: /app/internal/service/destinations/update_destination.sql
-- name: DestinationsServiceUpdateDestination :one
UPDATE destinations
SET
  name = COALESCE(sqlc.narg('name'), name),
  bucket_name = COALESCE(sqlc.narg('bucket_name'), bucket_name),
  region = COALESCE(sqlc.narg('region'), region),
  endpoint = COALESCE(sqlc.narg('endpoint'), endpoint),
  access_key = CASE
    WHEN sqlc.narg('access_key')::TEXT IS NOT NULL
    THEN pgp_sym_encrypt(sqlc.narg('access_key')::TEXT, sqlc.arg('encryption_key')::TEXT)
    ELSE access_key
  END,
  secret_key = CASE
    WHEN sqlc.narg('secret_key')::TEXT IS NOT NULL
    THEN pgp_sym_encrypt(sqlc.narg('secret_key')::TEXT, sqlc.arg('encryption_key')::TEXT)
    ELSE secret_key
  END
WHERE id = @id
RETURNING *;


-- file: /app/internal/service/destinations/test_destination.sql
-- name: DestinationsServiceSetTestData :exec
UPDATE destinations
SET test_ok = @test_ok,
    test_error = @test_error,
    last_test_at = NOW()
WHERE id = @destination_id;


-- file: /app/internal/service/destinations/paginate_destinations.sql
-- name: DestinationsServicePaginateDestinationsCount :one
SELECT COUNT(*) FROM destinations;

-- file: /app/internal/service/destinations/paginate_destinations.sql
-- name: DestinationsServicePaginateDestinations :many
SELECT
  *,
  pgp_sym_decrypt(access_key, @encryption_key) AS decrypted_access_key,
  pgp_sym_decrypt(secret_key, @encryption_key) AS decrypted_secret_key
FROM destinations
ORDER BY created_at DESC
LIMIT sqlc.arg('limit') OFFSET sqlc.arg('offset');


-- file: /app/internal/service/destinations/get_destinations_qty.sql
-- name: DestinationsServiceGetDestinationsQty :one
SELECT 
  COUNT(*) AS all,
  COALESCE(SUM(CASE WHEN test_ok = true THEN 1 ELSE 0 END), 0)::INTEGER AS healthy,
  COALESCE(SUM(CASE WHEN test_ok = false THEN 1 ELSE 0 END), 0)::INTEGER AS unhealthy
FROM destinations;


-- file: /app/internal/service/destinations/get_destination.sql
-- name: DestinationsServiceGetDestination :one
SELECT
  *,
  pgp_sym_decrypt(access_key, @encryption_key) AS decrypted_access_key,
  pgp_sym_decrypt(secret_key, @encryption_key) AS decrypted_secret_key
FROM destinations
WHERE id = @id;


-- file: /app/internal/service/destinations/get_all_destinations.sql
-- name: DestinationsServiceGetAllDestinations :many
SELECT
  *,
  pgp_sym_decrypt(access_key, @encryption_key) AS decrypted_access_key,
  pgp_sym_decrypt(secret_key, @encryption_key) AS decrypted_secret_key
FROM destinations
ORDER BY created_at DESC;


-- file: /app/internal/service/destinations/delete_destination.sql
-- name: DestinationsServiceDeleteDestination :exec
DELETE FROM destinations
WHERE id = @id;


-- file: /app/internal/service/destinations/create_destination.sql
-- name: DestinationsServiceCreateDestination :one
INSERT INTO destinations (
  name, bucket_name, region, endpoint,
  access_key, secret_key
)
VALUES (
  @name, @bucket_name, @region, @endpoint,
  pgp_sym_encrypt(@access_key, @encryption_key),
  pgp_sym_encrypt(@secret_key, @encryption_key)
)
RETURNING *;


-- file: /app/internal/service/databases/update_database.sql
-- name: DatabasesServiceUpdateDatabase :one
UPDATE databases
SET
  name = COALESCE(sqlc.narg('name'), name),
  pg_version = COALESCE(sqlc.narg('pg_version'), pg_version),
  connection_string = CASE
    WHEN sqlc.narg('connection_string')::TEXT IS NOT NULL
    THEN pgp_sym_encrypt(
      sqlc.narg('connection_string')::TEXT, sqlc.arg('encryption_key')::TEXT
    )
    ELSE connection_string
  END
WHERE id = @id
RETURNING *;


-- file: /app/internal/service/databases/test_database.sql
-- name: DatabasesServiceSetTestData :exec
UPDATE databases
SET test_ok = @test_ok,
    test_error = @test_error,
    last_test_at = NOW()
WHERE id = @database_id;


-- file: /app/internal/service/databases/paginate_databases.sql
-- name: DatabasesServicePaginateDatabasesCount :one
SELECT COUNT(*) FROM databases;

-- file: /app/internal/service/databases/paginate_databases.sql
-- name: DatabasesServicePaginateDatabases :many
SELECT
  *,
  pgp_sym_decrypt(connection_string, @encryption_key) AS decrypted_connection_string
FROM databases
ORDER BY created_at DESC
LIMIT sqlc.arg('limit') OFFSET sqlc.arg('offset');


-- file: /app/internal/service/databases/get_databases_qty.sql
-- name: DatabasesServiceGetDatabasesQty :one
SELECT 
  COUNT(*) AS all,
  COALESCE(SUM(CASE WHEN test_ok = true THEN 1 ELSE 0 END), 0)::INTEGER AS healthy,
  COALESCE(SUM(CASE WHEN test_ok = false THEN 1 ELSE 0 END), 0)::INTEGER AS unhealthy
FROM databases;


-- file: /app/internal/service/databases/get_database.sql
-- name: DatabasesServiceGetDatabase :one
SELECT
  *,
  pgp_sym_decrypt(connection_string, @encryption_key) AS decrypted_connection_string
FROM databases
WHERE id = @id;


-- file: /app/internal/service/databases/get_all_databases.sql
-- name: DatabasesServiceGetAllDatabases :many
SELECT
  *,
  pgp_sym_decrypt(connection_string, @encryption_key) AS decrypted_connection_string
FROM databases
ORDER BY created_at DESC;


-- file: /app/internal/service/databases/delete_database.sql
-- name: DatabasesServiceDeleteDatabase :exec
DELETE FROM databases
WHERE id = @id;


-- file: /app/internal/service/databases/create_database.sql
-- name: DatabasesServiceCreateDatabase :one
INSERT INTO databases (
  name, connection_string, pg_version
)
VALUES (
  @name, pgp_sym_encrypt(@connection_string, @encryption_key), @pg_version
)
RETURNING *;


-- file: /app/internal/service/backups/update_backup.sql
-- name: BackupsServiceUpdateBackup :one
UPDATE backups
SET
  name = COALESCE(sqlc.narg('name'), @name),
  cron_expression = COALESCE(sqlc.narg('cron_expression'), cron_expression),
  time_zone = COALESCE(sqlc.narg('time_zone'), time_zone),
  is_active = COALESCE(sqlc.narg('is_active'), is_active),
  dest_dir = COALESCE(sqlc.narg('dest_dir'), dest_dir),
  retention_days = COALESCE(sqlc.narg('retention_days'), retention_days),
  opt_data_only = COALESCE(sqlc.narg('opt_data_only'), opt_data_only),
  opt_schema_only = COALESCE(sqlc.narg('opt_schema_only'), opt_schema_only),
  opt_clean = COALESCE(sqlc.narg('opt_clean'), opt_clean),
  opt_if_exists = COALESCE(sqlc.narg('opt_if_exists'), opt_if_exists),
  opt_create = COALESCE(sqlc.narg('opt_create'), opt_create),
  opt_no_comments = COALESCE(sqlc.narg('opt_no_comments'), opt_no_comments)
WHERE id = @id
RETURNING *;


-- file: /app/internal/service/backups/toggle_is_active.sql
-- name: BackupsServiceToggleIsActive :one
UPDATE backups
SET is_active = NOT is_active
WHERE id = @backup_id
RETURNING *;


-- file: /app/internal/service/backups/schedule_all.sql
-- name: BackupsServiceGetScheduleAllData :many
SELECT 
  id,
  is_active,
  cron_expression,
  time_zone
FROM backups
ORDER BY created_at DESC;


-- file: /app/internal/service/backups/paginate_backups.sql
-- name: BackupsServicePaginateBackupsCount :one
SELECT COUNT(*) FROM backups;

-- file: /app/internal/service/backups/paginate_backups.sql
-- name: BackupsServicePaginateBackups :many
SELECT
  backups.*,
  databases.name AS database_name,
  destinations.name AS destination_name
FROM backups
INNER JOIN databases ON backups.database_id = databases.id
LEFT JOIN destinations ON backups.destination_id = destinations.id
ORDER BY backups.created_at DESC
LIMIT sqlc.arg('limit') OFFSET sqlc.arg('offset');


-- file: /app/internal/service/backups/get_backups_qty.sql
-- name: BackupsServiceGetBackupsQty :one
SELECT 
  COUNT(*) AS all,
  COALESCE(SUM(CASE WHEN is_active = true THEN 1 ELSE 0 END), 0)::INTEGER AS active,
  COALESCE(SUM(CASE WHEN is_active = false THEN 1 ELSE 0 END), 0)::INTEGER AS inactive
FROM backups;


-- file: /app/internal/service/backups/get_backup.sql
-- name: BackupsServiceGetBackup :one
SELECT * FROM backups
WHERE id = @id;


-- file: /app/internal/service/backups/get_all_backups.sql
-- name: BackupsServiceGetAllBackups :many
SELECT * FROM backups
ORDER BY created_at DESC;


-- file: /app/internal/service/backups/duplicate_backup.sql
-- name: BackupsServiceDuplicateBackup :one
INSERT INTO backups
SELECT (
  backups
  #= hstore('id', uuid_generate_v4()::text)
  #= hstore('name', (backups.name || ' (copy)')::text)
  #= hstore('is_active', false::text)
  #= hstore('created_at', now()::text)
  #= hstore('updated_at', now()::text)
).*
FROM backups
WHERE backups.id = @backup_id
RETURNING *;


-- file: /app/internal/service/backups/delete_backup.sql
-- name: BackupsServiceDeleteBackup :exec
DELETE FROM backups
WHERE id = @id;


-- file: /app/internal/service/backups/create_backup.sql
-- name: BackupsServiceCreateBackup :one
INSERT INTO backups (
  database_id, destination_id, is_local, name, cron_expression, time_zone,
  is_active, dest_dir, retention_days, opt_data_only, opt_schema_only,
  opt_clean, opt_if_exists, opt_create, opt_no_comments
)
VALUES (
  @database_id, @destination_id, @is_local, @name, @cron_expression, @time_zone,
  @is_active, @dest_dir, @retention_days, @opt_data_only, @opt_schema_only,
  @opt_clean, @opt_if_exists, @opt_create, @opt_no_comments
)
RETURNING *;


-- file: /app/internal/service/auth/login.sql
-- name: AuthServiceLoginGetUserByEmail :one
SELECT * FROM users WHERE email = @email;

-- file: /app/internal/service/auth/login.sql
-- name: AuthServiceLoginCreateSession :one
INSERT INTO sessions (
  user_id, token, ip, user_agent
) VALUES (
  @user_id, pgp_sym_encrypt(@token::TEXT, @encryption_key::TEXT), @ip, @user_agent
) RETURNING *, pgp_sym_decrypt(token, @encryption_key::TEXT) AS decrypted_token;


-- file: /app/internal/service/auth/get_user_sessions.sql
-- name: AuthServiceGetUserSessions :many
SELECT * FROM sessions WHERE user_id = @user_id ORDER BY created_at DESC;


-- file: /app/internal/service/auth/get_user_by_token.sql
-- name: AuthServiceGetUserByToken :one
SELECT
  users.*,
  sessions.id as session_id
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE pgp_sym_decrypt(sessions.token, @encryption_key) = @token::TEXT;


-- file: /app/internal/service/auth/delete_session.sql
-- name: AuthServiceDeleteSession :exec
DELETE FROM sessions WHERE id = @id;


-- file: /app/internal/service/auth/delete_old_sessions.sql
-- name: AuthServiceDeleteOldSessions :exec
DELETE FROM sessions WHERE created_at <= @date_threshold;


-- file: /app/internal/service/auth/delete_all_user_sessions.sql
-- name: AuthServiceDeleteAllUserSessions :exec
DELETE FROM sessions WHERE user_id = @user_id;


