name: CI (Lint, Test, Build)
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci:
    name: Lint, test, and build the code
    runs-on: ubuntu-24.04
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v4
        with:
          use: true

      - name: Build the Docker image
        run: >
          docker buildx build
          --load
          --platform linux/amd64
          --tag pgbackweb:latest
          --file docker/Dockerfile.dev .

      - name: Run lint, test, and build
        run: docker run --rm -v $PWD:/app pgbackweb:latest /bin/bash -c "cd /app && task ci"
